### ISSUE TITLE
Patch for /Contrib/Language files/Unicode/Welsh.nsh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimpark/unsis#38]
```
Cywiriadau, cysoni, byrhau, ayb. / Minor corrections, synchronization, 
shortening, etc.
```

Original issue reported on code.google.com by `a...@aledpowell.com` on 3 Jan 2015 at 3:56

Attachments:
* [Welsh.nsh.patch](https://storage.googleapis.com/google-code-attachments/unsis/issue-38/comment-0/Welsh.nsh.patch)

**Comment by jimpark** [comment]
Applied the patch. Thank you!
