### ISSUE TITLE
Update or new version NSIS Unicode ?!

### ISSUE THREAD

**Issue by MaGoth** [jimpark/unsis#42]
NSIS 2.47 released December 8, 2015
http://sourceforge.net/p/nsis/news/2015/12/nsis-247-released/

NSIS 2.48 Released December 10, 2015
http://sourceforge.net/p/nsis/news/2015/12/nsis-248-released/

Tnx.

**Comment by lordmulder** [comment]
I second the request of updating Unicode NSIS to v2.48 :+1:

**Comment by MaGoth** [comment]
Up..
NSIS 2.49 Released December 16, 2015
http://sourceforge.net/p/nsis/news/2015/12/nsis-249-released/

**Comment by gene7299** [comment]
Does NSIS native support unicode?

**Comment by lordmulder** [comment]
> Does NSIS native support unicode?

NSIS 2.x does **not**, thus the *Unicode NSIS* for has been created. The upcoming NSIS 3.x will support both, ANSI and Unicode (UTF-16). It  basically adopted most of the *Unicode NSIS* changes.

**Comment by jimpark** [comment]
Looks like 2.49 just came out. Maybe it's better to wait until activity dies down before porting the changes.

**Comment by MaGoth** [comment]
Up..
NSIS 2.50 Released December 26, 2015
http://sourceforge.net/p/nsis/news/2015/12/nsis-250-released/

**Comment by uroni** [comment]
Looks like the last one fixes a security issue, so I'd appreciate if this is priorized (http://sourceforge.net/p/nsis/bugs/1125/ )

**Comment by jimpark** [comment]
It looks like that particular security issue I've already addressed years ago. But I am working on the port of the 2.50 code base right now.
